# Generated by Django 6.0.5 on 2026-05-27 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_person',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_phone',
            new_name='phone',
        ),
    ]
